### ISSUE TITLE
Thematic alert modals

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-app#270] opened 2017-03-23 17:06 UTC
Replace all alerts with thematic modals

Ties in with exposing additional alerts:
- network errors: https://github.com/ExpeditionRPG/expedition-app/issues/142
- XML parse errors: https://github.com/ExpeditionRPG/expedition-app/issues/154

**Comment by smartin015** [comment] 2017-05-06 15:34
Dupe of #142

**Closed by smartin015** 2017-05-06 15:34 UTC
Labels: enhancement
